"""update models

Revision ID: 3ff3bf73f80d
Revises: 608aa1300463
Create Date: 2024-02-13 19:03:16.093953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff3bf73f80d'
down_revision: Union[str, None] = '608aa1300463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'products',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'products',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
