"""update models

Revision ID: a6df54c7e2ce
Revises: a902c0e0e1fd
Create Date: 2024-02-13 13:05:35.815046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6df54c7e2ce'
down_revision: Union[str, None] = 'a902c0e0e1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('payment_type', sa.String(), nullable=False))
    op.add_column('receipts', sa.Column('payment_amount', sa.Float(), nullable=False))
    op.add_column('receipts', sa.Column('products', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'products')
    op.drop_column('receipts', 'payment_amount')
    op.drop_column('receipts', 'payment_type')
    # ### end Alembic commands ###
